Remove all linter excluding rules. Fix all linter issues that appeare…
skycoin/dmsg-deprecated pull request #23
Opened 2019-07-15 12:29 UTC by nkryuchkov

Fixes #22 

 Changes:	
- Removed all linter excluding rules
- Removed all `nolint` comments except a couple of them that are really necessary
- Fixed all linter issues after removal
- Made some code cleanup

2019-07-16 07:19 UTC, evanlinjin approved these changes

2019-07-16 07:19 UTC, evanlinjin commented on client_test.go
> +		serveErrCh1 := make(chan error, 1)
I prefer the following pattern:
```golang
done1 := make(chan struct{})
var err1 error
go func () {
    err1 = conn1.Server(ctx, ch1)
    close(done1)
}()
<-done1

```
As it ensures the good habit of closing channels after they are created.

2019-07-16 07:53 UTC, ivcosla approved these changes
good job

2019-07-16 08:03 UTC, nkryuchkov commented on client_test.go
> +		serveErrCh1 := make(chan error, 1)
@evanlinjin What if we close the `serveErrCh1` channel after sending to it an error returned by `Serve`? I think this way we can reduce the amount of code

2019-07-19 08:55 UTC, evanlinjin commented on client_test.go
> +		serveErrCh1 := make(chan error, 1)
> @evanlinjin What if we close the `serveErrCh1` channel after sending to it an error returned by `Serve`? I think this way we can reduce the amount of code

I guess that can work too.

2019-07-19 09:08 UTC, nkryuchkov commented on client_test.go
> +		serveErrCh1 := make(chan error, 1)
@evanlinjin Fixed

2019-07-19 09:42 UTC, evanlinjin requested changes
Good stuff. One more small thing.

2019-07-19 09:42 UTC, evanlinjin commented on noise/net_test.go
> +		require.NoError(t, d.Close())
I think it is better if we don't check this error. Line 91 also closes the same connection, and hence, this may return an error.

2019-07-19 09:48 UTC, nkryuchkov commented on noise/net_test.go
> +		require.NoError(t, d.Close())
@evanlinjin Thanks for pointing out. Fixed.

2019-07-19 09:54 UTC, evanlinjin approved these changes

2019-07-19 09:55 UTC, merged