[WIP] [ROUTING] Implement ports and have a separate structure for Listeners.
skycoin/dmsg-deprecated pull request #30
Opened 2019-08-02 08:53 UTC by nkryuchkov

Fixes #28 

This is an early draft, doesn't work yet and needs further improvements.

Changes:	
- Partially implement ports

TODO:
- Separate `dmsg.Listener`
- Finish issues in ports implementation

2019-08-11 16:28 UTC, evanlinjin commented on client_conn.go
> +	case lis.(*listener).accept <- tp:
Is this an accidental code duplication with the case in line 169?

2019-08-12 08:11 UTC, nkryuchkov commented on client_conn.go
> +	case lis.(*listener).accept <- tp:
@evanlinjin yeah, it looks like I merged new changes incorrectly here. Thanks.

2019-08-12 10:10 UTC, evanlinjin requested changes
Overall the code is clean. Please check out my queries. There will be more on the way.

2019-08-12 10:10 UTC, evanlinjin commented on client_conn.go
> +func NewClientConn(log *logging.Logger, conn net.Conn, local, remote cipher.PubKey, pm *PortManager) *ClientConn {
Let's not have `pm *PortManager` as an input. Instead, have the `PortManager` created in the function.

2019-08-12 10:10 UTC, evanlinjin commented on client_conn.go
> +	payload, err := unmarshalHandshakePayload(p)
Just for future reference, I think a bit more thought can be put into lines 137-148, maybe even the lines from 218 to 226 can be cleaned up. This can be made into an issue.

2019-08-12 10:10 UTC, evanlinjin commented on listener.go
> +type Listener interface {
These interfaces are meant to be *theoretical*, meaning that these structures are to implement these interfaces, but these interfaces are not to be defined.

Let's get rid of `Listener`, `Factory` and `Transport` interface definitions, and rename `listener`, `factory` and `transport`to `Listener`, `Factory` and `Transport`. Thanks!

2019-08-12 10:10 UTC, evanlinjin commented on server.go
>  		log = log.WithField("received", f)
If I'm not mistaken, instead of having a `var logMu sync.RWMutex`, we can just add a colon here.
```golang
log := log.WithField("received", f)
```
That should get rid of the data races.

2019-08-12 10:10 UTC, evanlinjin commented on client_conn.go
> +	payload, err := unmarshalHandshakePayload(p)
And if there is an unmarshaling error, it can be the following:
- A mistake by the `dmsg.Server` is made (as the server should check all requests). 
- The versions of `dmsg.Client` and `dmsg.Server` are different.
- Some malicious activity.

In all these cases, the `dmsg.Client` should just disconnect from the `dmsg.Server`.

2019-08-12 10:35 UTC, evanlinjin requested changes
More comments. My next step is to actually test out the codebase. Will keep you posted.

2019-08-12 10:35 UTC, evanlinjin commented on listener.go
> +			select {
From my experience, even with this type of select statement, there is still a possibility for a race condition with the `accept` chan. Specifically, it will be the `write`/`close` conflict.

For the solution, we probably need to introduce a `sync.Mutex` and add a `l.IntroduceTransport(Transport) error` member (that includes the logic of writing to `l.accept`).

As an example, please check out `transport.inMx` and `transport.inCh`.

2019-08-12 10:35 UTC, evanlinjin commented on frame.go
> +	ReasonErr = iota
Rename to `PlaceholderReason`.

2019-08-13 02:24 UTC, evanlinjin commented on client_conn.go
> +func NewClientConn(log *logging.Logger, conn net.Conn, local, remote cipher.PubKey, pm *PortManager) *ClientConn {
I take this back.

2019-08-13 06:42 UTC, nkryuchkov commented on server.go
>  		log = log.WithField("received", f)
@evanlinjin Good idea, thanks! Fixed.

2019-08-13 09:52 UTC, nkryuchkov commented on listener.go
> +			select {
@evanlinjin Good idea, done.

2019-08-13 09:55 UTC, nkryuchkov commented on client_conn.go
> +	payload, err := unmarshalHandshakePayload(p)
@evanlinjin Don't you mind if it would be done in this PR?

2019-08-13 10:02 UTC, evanlinjin commented on client_conn.go
> +	payload, err := unmarshalHandshakePayload(p)
@nkryuchkov If you have an idea :D

2019-08-13 10:03 UTC, evanlinjin approved these changes
Looks good. Just make Travis happy.

2019-08-15 22:28 UTC, evanlinjin commented on client.go
> +		done:   c.done,
This implementation is not acceptable. `c.done` will be closed multiple times in this manner.

2019-08-15 23:59 UTC, evanlinjin requested changes
Note that `dmsg.Transport`s should each be represented by 2 public keys and 2 ports.
- The local address should be of form: `<local public key>:<local port>`
- The remote address should be of form: `<remote public key>:<remote port>`

This is because we are to try emulate the behavior of TCP as closely as possible. In other words, when we `Dial`, we should assign a local ephemeral port.

I've already made a start to these changes here: #33 (feel free to merge it in here).
> *p.s. These changes were done so `dmsg` can work with my changes to `skywire` repo: https://github.com/skycoin/skywire/pull/517*

However the following things still need to done:
- The [`PortManager.listeners`](https://github.com/evanlinjin/dmsg/blob/4051684fd51c502447bdfd2beef3aad8856b9091/port_manager.go#L20) map should use a key made up of the combination of the local and remote ports of the `dmsg.Transport`. Let's do it in this manner: `type tpID [4]byte` (where it contains 2 ports encoded `<local-port>:<remote-port>`).
- [`HandshakePayload`](https://github.com/evanlinjin/dmsg/blob/4051684fd51c502447bdfd2beef3aad8856b9091/frame.go#L39-L44) should also have a local port.

Eventually we can get rid of [`Transport.id`](https://github.com/evanlinjin/dmsg/blob/4051684fd51c502447bdfd2beef3aad8856b9091/transport.go#L31) altogether as we can use `type tpID [4]byte` to replace it.
> However if you don't feel confident doing this, we can do it later on. Otherwise, feel free to make it a part of this PR.

2019-08-16 06:08 UTC, evanlinjin commented
> Note that `dmsg.Transport`s should each be represented by 2 public keys and 2 ports.
> 
>     * The local address should be of form: `<local public key>:<local port>`
> 
>     * The remote address should be of form: `<remote public key>:<remote port>`
> 
> 
> This is because we are to try emulate the behavior of TCP as closely as possible. In other words, when we `Dial`, we should assign a local ephemeral port.
> 
> I've already made a start to these changes here: #33 (feel free to merge it in here).
> 
> > _p.s. These changes were done so `dmsg` can work with my changes to `skywire` repo: [skycoin/skywire#517](https://github.com/skycoin/skywire/pull/517)_
> 
> However the following things still need to done:
> 
>     * The [`PortManager.listeners`](https://github.com/evanlinjin/dmsg/blob/4051684fd51c502447bdfd2beef3aad8856b9091/port_manager.go#L20) map should use a key made up of the combination of the local and remote ports of the `dmsg.Transport`. Let's do it in this manner: `type tpID [4]byte` (where it contains 2 ports encoded `<local-port>:<remote-port>`).
> 
>     * [`HandshakePayload`](https://github.com/evanlinjin/dmsg/blob/4051684fd51c502447bdfd2beef3aad8856b9091/frame.go#L39-L44) should also have a local port.
> 
> 
> Eventually we can get rid of [`Transport.id`](https://github.com/evanlinjin/dmsg/blob/4051684fd51c502447bdfd2beef3aad8856b9091/transport.go#L31) altogether as we can use `type tpID [4]byte` to replace it.
> 
> > However if you don't feel confident doing this, we can do it later on. Otherwise, feel free to make it a part of this PR.

Change of plan.

I realized it will be a hassle to properly implement ports, and the solution we have now is good enough and works perfectly well. Let's leave it as is :)

2019-08-20 08:37 UTC, ivcosla approved these changes
Very good job here!

2019-08-26 02:57 UTC, evanlinjin commented
Closed for now, as these changes are already in `mainnet-milestone1` branch.

2019-08-26 02:57 UTC, closed without merging