Fix error returned from serve
skycoin/dmsg-deprecated pull request #6
Opened 2019-06-28 10:16 UTC by Darkren

Fixes #3

`done` channel was added to `Server` along with the mx to prevent concurrent read/close operations. Func `IsClosed` was added

2019-06-28 13:02 UTC, Darkren commented
If I put `doneMx.Unlock()` into defer in the `Close` func, it causes deadlock. `wg.Wait` is being locked in `Close` preventing the release of `doneMx`, while `IsClosed` is waiting for `doneMx` in `Serve`. I think it should be sorted out

2019-06-28 20:11 UTC, nkryuchkov approved these changes
Looks good to me, well done! I'd rename some variables, however, I think it could be merged as it is because https://github.com/skycoin/dmsg/pull/2 needs changes anyway after this PR is merged.

2019-06-28 20:11 UTC, nkryuchkov commented on server_test.go
>  		a := NewClient(aPK, aSK, dc, SetLogger(logging.MustGetLogger("A")))
What do you think about renaming all variables containing `a`/`b` to something like `responder`/`initiator` or `resp`/`init`. I think it might be more readable.

2019-06-30 08:16 UTC, evanlinjin requested changes

2019-06-30 08:16 UTC, evanlinjin commented on server.go
> +	if err := s.closeListener(); err != nil {
Let's not have separate functions for `closeListener` and `clearConns`. Personally, I think the logic here is simple enough to have everything in one function.

2019-06-30 08:16 UTC, evanlinjin commented on server.go
> +	doneMx sync.Mutex
using `sync.Once` will probably be more elegant here.

Have a `s.close() (closed bool, err error)` that closes `s.lis` once, and does `s.conns = make(map[cipher.PubKey]*ServerConn)`.

Then `Close()` will look the following (note that `wg.Wait()` is outside `once.Do()` to avoid hang):
```golang
func (s *Server) Close() error {
	closed, err := s.close()
	if !closed {
		err = errors.New("server already closed")
	}
	s.wg.Wait()
	return err
}
```
And error-handling within `s.Serve()`...
```golang
rawConn, err := s.lis.Accept()
if err != nil {
	if err == io.ErrUnexpectedEOF {
		continue
	}
	if closed, err := s.close(); !closed {
		return err
	}
	return nil
}
```

2019-06-30 08:32 UTC, evanlinjin commented on server.go
> +	doneMx sync.Mutex
And if you use `done chan struct{}`, I don't think `doneMx` is needed.
1. We are not concurrently doing write/close operations.
2. We just need to ensure we `close(s.done)` before doing `s.lis.Close()`.

However, I do prefer the solution using `sync.Once`.

2019-06-30 08:33 UTC, evanlinjin commented on server.go
>  			if err == io.ErrUnexpectedEOF {
I know you aen't to blame for this, but this can be removed as we are handling this within `noise.Listener` now.

2019-06-30 08:35 UTC, Darkren commented on server.go
>  			if err == io.ErrUnexpectedEOF {
@evanlinjin the whole purpose of this PR was to add this check. If this handled by `noise.Listener`, this is not needed at all, I'll check

2019-06-30 08:37 UTC, evanlinjin commented on server.go
>  			if err == io.ErrUnexpectedEOF {
Are we on the same page? Do you mean `err == io.ErrUnexpectedEOF` ?

2019-06-30 08:37 UTC, Darkren commented on server.go
>  			if err == io.ErrUnexpectedEOF {
@evanlinjin ah, no, I messed up, nvm

2019-06-30 08:41 UTC, Darkren commented on server.go
> +	doneMx sync.Mutex
@evanlinjin in the current state `doneMx` is really needed. It's purpose here is to separate read/close opeartions, no matter how strange this may sound to you, this is what was intended. We have read operation in `IsClosed` and we have close operation in `Close`. We need to close the `done` channel right after the socket is closed, but while it is in the process of closing, we don't want read operations to occur. Simply, the channel won't get closed in time, thus `IsClosed` will return false leading to the error being returned from `Serve`. Removing `doneMx` causes the data race in this particular case. Although I will take a look at you suggestion with `sync.Once`, maybe this will help

2019-06-30 08:47 UTC, evanlinjin commented on server.go
> +	doneMx sync.Mutex
> We need to close the `done` channel right after the socket is closed,
Why does it need to be in such an order? Can't we close `done` before closing the socket?

2019-06-30 08:49 UTC, Darkren commented on server.go
> +	doneMx sync.Mutex
@evanlinjin I thought of it. This would be an easy solution and will let us get rid of `doneMx`. But it seems unlogical to me. `done` is indicating that the server is already stopped, but it's not in this case. If you think that it doesn't really matter, I may close `done` before the socket and everything should be fine

2019-06-30 09:03 UTC, evanlinjin commented on server.go
> +	doneMx sync.Mutex
From your definition, I guess a better name for `done chan struct{}` would be `isClosing` or something. But I think `done` is common so we should stick with it.

But thinking about it from another perspective, `done` can be a part of a sentence such as; *is to be done*.

Although is you are going with the `sync.Once` solution, we won't need `done` altogether.

2019-06-30 09:05 UTC, Darkren commented on server.go
> +	doneMx sync.Mutex
@evanlinjin yeah, but `isClosing` should signal `true` just for a short period of time and then again start signaling `false` while the other `done` should start signaling `true`, this will give us the whole picture. But anyway, I'll try to do this with `sync.Once` and let you know

2019-06-30 09:10 UTC, evanlinjin commented on server.go
> +	doneMx sync.Mutex
```golang
type Server struct {
    closeInitiated chan struct{}
}
```

2019-06-30 09:50 UTC, Darkren commented on server.go
> +	doneMx sync.Mutex
@evanlinjin hm, as I can see, we still need some kind of flag indicating that the server is done. If we do as you suggested, than `close` will return `true` only once, when it is called for the first time. But the first time it's intented to be called from `Close`. This way when we get an error from the listener and call `close`, it will be the second call which will result in `false`, thus returning the unwanted error from `Serve`. Probably we should have the bool being returned from `close` as a field in the `Server` struct, so it will give us the same value each time `close` is called. But it will ruin the thought you put into this `close`. What if we do it the following way. Let's say, we have this:
```
type Server struct {
    closeInitiated int32
    done int32
}
```

Then the `Close` will be:
```
func (s *Server) Close() (err error) {
        if atomic.LoadInt32(&s.done) == 1 {
                return erros.New("server is already closed")
        }

        if !atomic.CompareAndSwapInt32(&s.closeInitiated, 0, 1) {
                return errors.New("server is already being closed")
        }

	if err := s.lis.Close(); err != nil {
                atomic.Store(&s.done, 1)
                atomic.Store(&s.closeInitiated, 0)
		return err
	}

        atomic.Store(&s.done, 1)
        atomic.Store(&s.closeInitiated, 0)

        s.mx.Lock()
	s.conns = make(map[cipher.PubKey]*ServerConn)
        s.mx.Unlock()

	s.wg.Wait()
	return nil
}
```

Then we may have both `IsBeingClosed` and `IsClosed` like this:
```
func (s *Server) IsBeingClosed () bool {
        return atomic.LoadInt32(&s.closeInitiated) == 1
}

func (s *Server) IsClosed() bool {
        return atomic.LoadInt32(&s.done) == 1
}
```

And `Serve` will be like:
```
rawConn, err := s.lis.Accept()
if err != nil {
	if s.IsBeingClosed() || s.IsClosed() {
		return nil
	}
	
        return err
}
```

Personally, I don't like the idea of addig a lot of funcs which may not ever be needed (e.g. `IsBeingClosed`). What do you think if we won't try to represent the state of the whole server? We actually don't have such a need, I added this func only to filter out the socket error. What if we just add the `socketIsClosed bool` field to a server and set it to `true` via the `sync.Once` in `Close`? And we may totally remove `IsClosed` in this case and leave it's implementation a subject for future discussions if it ever gets really needed

2019-06-30 15:21 UTC, Darkren commented on server.go
> +	doneMx sync.Mutex
I pushed an example of what I think of here. We have `lisDone` to indicate whether the socket is closed and the corresponding func `isLisClosed`. Value is read/written via atomics. Also I kept `sync.Once` as you've suggested in `Close` in case of misuse of `Close`. If the `IsClosed` func gets ever needed it may be simply injected into this mechanism as it's done in `Transport`

2019-06-30 15:21 UTC, Darkren commented on server.go
>  			if err == io.ErrUnexpectedEOF {
Removed

2019-06-30 15:23 UTC, Darkren commented on server_test.go
>  		a := NewClient(aPK, aSK, dc, SetLogger(logging.MustGetLogger("A")))
@nkryuchkov I think it's a subject to discuss with @evanlinjin , the names used here correspond to the ones described in `TESTING.md`. I'm not really against of renaming variables, but I think that they should also be renamed in `TESTING.md` if we decide to do this

2019-07-01 09:44 UTC, evanlinjin commented on server_test.go
>  		a := NewClient(aPK, aSK, dc, SetLogger(logging.MustGetLogger("A")))
@Darkren I like the `resp`/`init` naming convention. Let's create a separate PR for this.

2019-07-01 09:45 UTC, evanlinjin commented on server.go
> +	doneMx sync.Mutex
@Darkren we definitely don't need to record any state. `IsClosed` and `IsClosing` won't be needed if we can have an implementation that handles closing `Serve` properly. I like what you have done in the PR.

2019-07-01 09:45 UTC, evanlinjin approved these changes

2019-07-01 09:46 UTC, evanlinjin commented
After the merge conflicts are resolved, we can merge.

2019-07-01 10:26 UTC, merged